name: my_utils
description: A new Flutter package project.
version: 0.0.1
homepage: none

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  fpdart: ^1.0.0
  logger: ^2.0.1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0




flutter:

  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
