name: Test

on:
  pull_request:
    branches:
      - master
      - dev
  push:
    branches:
      - "**"
      # - dev
      - "!master"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.12.0
        with:
          flutter-version: stable

      - run: flutter --version

      - name: clean
        run: flutter clean

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test
